// File generated by flutterfire configure command.
// This file is suitable for committing to a version control system.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb;
import 'package:flutter/material.dart' show TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA75mAweZZHfCA1r1jOhUBLYmJAgdiSnqE',
    appId: '1:714989301859:web:61e3419a6160f235fb4856',
    messagingSenderId: '714989301859',
    projectId: 'suan-16f16',
    authDomain: 'suan-16f16.firebaseapp.com',
    storageBucket: 'suan-16f16.firebasestorage.app',
    measurementId: 'G-6QZV4G7RGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqOl-cHklAVjIyFW4IdvwKBj_8ia1qPMs',
    appId: '1:714989301859:android:139aeb6d3416a516fb4856',
    messagingSenderId: '714989301859',
    projectId: 'suan-16f16',
    storageBucket: 'suan-16f16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsieLKXD0n5sWnu9J_UXieRlcv7YLVijA',
    appId: '1:714989301859:ios:eb8ceccbe832721bfb4856',
    messagingSenderId: '714989301859',
    projectId: 'suan-16f16',
    storageBucket: 'suan-16f16.firebasestorage.app',
    iosBundleId: 'com.example.suan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsieLKXD0n5sWnu9J_UXieRlcv7YLVijA',
    appId: '1:714989301859:ios:eb8ceccbe832721bfb4856',
    messagingSenderId: '714989301859',
    projectId: 'suan-16f16',
    storageBucket: 'suan-16f16.firebasestorage.app',
    iosBundleId: 'com.example.suan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA75mAweZZHfCA1r1jOhUBLYmJAgdiSnqE',
    appId: '1:714989301859:web:8e75c0886f070826fb4856',
    messagingSenderId: '714989301859',
    projectId: 'suan-16f16',
    authDomain: 'suan-16f16.firebaseapp.com',
    storageBucket: 'suan-16f16.firebasestorage.app',
    measurementId: 'G-T6ZLFDLQ2F',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey1234567890abcdefghijklmnop',
    appId: '1:123456789012:linux:abcdefghijklmnopqrstu',
    messagingSenderId: '123456789012',
    projectId: 'suan-app-demo',
    storageBucket: 'suan-app-demo.appspot.com',
  );
}